

- hosts: all
  connection: local

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
    ansible_connection=network_cli
    ansible_network_os=junos


  tasks:
        
    - name: configure static route
      junos_static_route:
        address: "{{ routing_network }}/{{ mask }}"
        next_hop: "{{ next_hop }}"
        state: "{{ state }}"
