

- hosts: all
  #connection: netconf

  vars: 
    ansible_connection: netconf
    ansible_network_os: junos
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"

  tasks:
    - name: Retrieve Junos OS version
      junos_command:
        commands: show version
        
    - name: configure static route
      connection: network_cli
      junos_static_route:
        address: 192.168.2.0/24
        next_hop: 10.0.0.1
        preference: 10
        qualified_next_hop: 10.0.0.2
        qualified_preference: 3
        state: present
            
    #- name: configure static route
    #  junos_static_route:
    #    address: 100.100.100.0/24
    #    next_hop: 100.100.100.1
    #    state: "{{ state }}"
    #  
    #    #address: "{{ routing_network }}/{{ mask }}"
        #next_hop: "{{ next_hop }}"
        #state: "{{ state }}"
