

- hosts: all
  connection: local

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"

  tasks:
        
    - name: configure static route
      junos_static_route:
        address: 100.100.100.0/24
        next_hop: 100.100.100.1
        state: "{{ state }}"
      
        #address: "{{ routing_network }}/{{ mask }}"
        #next_hop: "{{ next_hop }}"
        #state: "{{ state }}"
