
- hosts: all
  connection: local

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"


  tasks:
        
    #- name: change static route
    #  vyos_config:
    #    lines:
    #      - "set protocols static route {{ routing_network }} next-hop {{ next_hop }}"
         
    - name: remove configuration
      vyos_static_route:
        prefix: {{ routing_network }}
        mask: {{ mask }}
        next_hop: {{ next_hop }}
        state: {{ state }}
