- hosts: all
  connection: local

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"


  tasks:
        
    - name: change static route
      vyos_config:
        lines:
          - "delete protocols static route {{ routing_network }}"
