


- hosts: all
  connection: local

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"


  tasks:
  
    - name: configure the remote device
      vyos_config:
        lines: set nat source rule 100 outbound-interface eth0
        
    - name: configure the remote device
      vyos_config:
        lines: set nat source rule 100 source address 192.168.0.0/24

    - name: configure the remote device
      vyos_config:
        lines: set nat source rule 100 translation address masquerade
