
- hosts: all
  connection: local

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"


  tasks:
  
    - name: configure the remote device
      vyos_config:
        lines:
          - set system host-name "{{ host }}"
        
    - name: for idempotency, use full-form commands
      vyos_config:
        lines:
          - set interfaces ethernet {{ set_eth }} address "{{ new_ip_address }}"
