


- hosts: all
  connection: local

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"


  tasks:
  
    - name: configure the remote device
      vyos_config:
        lines:
          - set interfaces ethernet eth0 description GLOBAL
          - set interfaces ethernet eth0 address 192.168.10.1/24
          - set interfaces ethernet eth0 description INTERNAL
          - set interfaces ethernet eth0 address 192.168.0.1/24
          - set protocols static route 0.0.0.0/0 next-hop 192.168.10.1
          - set nat source rule 100 outbound-interface eth0
          - set nat source rule 100 source address 192.168.0.0/24
          - set nat source rule 100 translation address masquerade

