- hosts: all
  connection: local

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"


  tasks:
    #- name: show configuration on ethernet devices eth0 and eth1
    #  vyos_command:
    #    commands:
    #      - show interfaces ethernet {{ item }}
    #  with_items:
    #    - eth0
    #    - eth1
        
    - name: show configuration on ethernet devices eth0 and eth1
      vyos_command:
        commands:
          - show configuration
      register: config_result
      
    - name: debug
      debug:
        msg: "{{ config_result.stdout_lines }}"

