
- hosts: all
  connection: local

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"


  tasks:
        
    - name: change static route
      vyos_config:
        lines:
          - {{ action }} protocols static route {{ routing_network }} next-hop {{ next_hop }}
